#!/bin/bash

CHROME_DRIVER=/usr/local/bin/chromedriver
JAVA_BINARY=/usr/bin/java
SELENIUM_SERVER_JAR=/usr/local/bin/selenium-server-standalone-3.5.3.jar

case $1 in

    start)
        $JAVA_BINARY -Dwebdriver.chrome="$CHROME_DRIVER" -jar $SELENIUM_SERVER_JAR
    ;;
esac